# Generated by Django 5.0.6 on 2024-07-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_address', models.CharField(max_length=255)),
                ('destination_address', models.CharField(max_length=255)),
                ('distance_km', models.FloatField()),
                ('search_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
